//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.LapHoaDons = new HashSet<LapHoaDon>();
        }
    
        public string maHD { get; set; }
        public System.DateTime ngayLapHD { get; set; }
        public string maPT { get; set; }
        public string maKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuThueSan PhieuThueSan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LapHoaDon> LapHoaDons { get; set; }
    }
}
