//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LapPhieu
    {
        public int soGioThue { get; set; }
        public System.DateTime NgayThue { get; set; }
        public string tenNVlapPhieu { get; set; }
        public string tenSanThue { get; set; }
        public string maNV { get; set; }
        public string maPT { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhieuThueSan PhieuThueSan { get; set; }
    }
}
