//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.LapHoaDons = new HashSet<LapHoaDon>();
            this.LapPhieux = new HashSet<LapPhieu>();
        }
    
        public string maNV { get; set; }
        public string hotenNV { get; set; }
        public string emailNV { get; set; }
        public string sdtNV { get; set; }
        public string diaChiNV { get; set; }
        public System.DateTime dobNV { get; set; }
        public System.DateTime ngayVaoLam { get; set; }
        public string maPH { get; set; }
        public int maCV { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LapHoaDon> LapHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LapPhieu> LapPhieux { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
